### ISSUE TITLE
Magic Value

### ISSUE THREAD

**Issue by rtc5200** [spigotjpwiki/spigotjpwiki.github.io#2]
deprecated(非推奨)の理由で、"Magic Value"と出てくるのですが、[マジックナンバー](http://ja.wikipedia.org/wiki/%E3%83%9E%E3%82%B8%E3%83%83%E3%82%AF%E3%83%8A%E3%83%B3%E3%83%90%E3%83%BC_%28%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0%29)という意味で,マジックナンバーと訳しても良いでしょうか

**Comment by spigotjpwiki** [comment]
マジックナンバーで大丈夫です。

**Comment by rtc5200** [comment]
了解しました.
